name=NoriegaIoT.Core
version=1.0.0
author=Mateo Noriega
maintainer=Mateo Noriega
sentence=Reusable core components for NoriegaIoT projects.
paragraph=Generic reusable components for ESP32 IoT projects.
category=Other
architectures=esp32